/**:
  ros__parameters:
    lane_change:
      lane_change_prepare_duration: 4.0         # [s]
      lane_changing_duration: 8.0               # [s]
      lane_change_finish_judge_buffer: 3.0      # [m]
      minimum_lane_change_velocity: 2.777         # [m/s]
      prediction_time_resolution: 0.5           # [s]
      maximum_deceleration: 1.0                 # [m/s2]
      lane_change_sampling_num: 10

      lane_changing_lateral_jerk: 0.5
      lane_changing_lateral_acc: 0.5

      # collision check
      # enable_collision_check_at_prepare_phase: false
      # prepare_phase_ignore_target_speed_thresh: 0.1 # [m/s]
      # use_predicted_path_outside_lanelet: true
      # use_all_predicted_path: true

      # abort
      enable_cancel_lane_change: true
      enable_abort_lane_change: false

      abort_lane_change_velocity_thresh: 0.5
      abort_lane_change_angle_thresh: 10.0      # [deg]
      abort_lane_change_distance_thresh: 0.3    # [m]

      abort_delta_time: 3.0                      # [s]
      abort_max_lateral_jerk: 2.0                # [m/s3]

      # debug
      publish_debug_marker: false
